### ISSUE TITLE
Unable to use quotaservice as a library due to vendored dependencies

### ISSUE THREAD

**Issue by hsheth2** [square/quotaservice#116]
I am trying to run quotaservice by using it as a library. While this works for a simple server with a memory bucket, it fails when trying to use the redis bucket due to vendored dependencies. 

The code I am running is very adapted from the `test/main.go` file. 
```
package main

import (
	"net/http"
	"os"
	"os/signal"
	"sync"
	"syscall"

	"github.com/square/quotaservice"
	"github.com/square/quotaservice/buckets/redis"
	"github.com/square/quotaservice/config"
	"github.com/square/quotaservice/rpc/grpc"
	"github.com/square/quotaservice/stats"

	redisClient "gopkg.in/redis.v5"
)

const (
	adminServer = "0.0.0.0:8080"
	redisServer = "redis:6379"
	gRPCServer  = "0.0.0.0:10990"
)

func main() {
	cfg := config.NewDefaultServiceConfig()

	server := quotaservice.New(redis.NewBucketFactory(&redisClient.Options{
		Addr: redisServer,
	}, 5, ""),
		config.NewMemoryConfig(cfg),
		config.NewReaperConfig(),
		0,
		grpc.New(gRPCServer))
	server.SetStatsListener(stats.NewMemoryStatsListener())
	if _, e := server.Start(); e != nil {
		panic(e)
	}

	// Block until SIGTERM or SIGINT
	sigs := make(chan os.Signal, 1)
	signal.Notify(sigs, syscall.SIGTERM, syscall.SIGINT)

	var shutdown sync.WaitGroup
	shutdown.Add(1)

	go func() {
		<-sigs
		shutdown.Done()
	}()

	shutdown.Wait()
	_, _ = server.Stop()
}
```

Because of the use of vendoring within quotaservice, I get the following error:
`./main.go:50:7: cannot use "gopkg.in/redis.v5".Options literal (type *"gopkg.in/redis.v5".Options) as type *"github.com/square/quotaservice/vendor/gopkg.in/redis.v5".Options in argument to "github.com/square/quotaservice/buckets/redis".NewBucketFactory`

**Comment by nicktrav** [comment]
cc: @maniksurtani @mpuncel

**Comment by mpuncel** [comment]
@hsheth2 I'm realizing from your question that I've never tried to import a library that has a `vendor/` dir from a project that doesn't have its own `vendor/`. It might be the case that this isn't possible given the way `vendor/` works.

Are you able to create a `vendor/` dir of your own? with `dep` it's as easy as installation and then `dep ensure` in the repo that has your `main.go`

**Comment by hsheth2** [comment]
Interestingly enough, Go does not complain once I created a `vendor/` directory with `dep`. Even if I use a version of redis.v5 different from what quotaservice uses, it does not complain about the discrepancy. 

That said, it seems that it is generally a bad practice to leak the usages of vendored dependencies in the public API, as is done by [quotaservice/buckets/redis](https://godoc.org/github.com/square/quotaservice/buckets/redis) with its `redis.v5` dependency.
